SELECT *FROM T_AGENT
UPDATE T_AGENT
set target_policy_sum=case
WHEN (AGENT_CITY='PUNE' AND AGENT_ID REGEXP '^[M]') THEN TARGET_POLICY_SUM=400000
WHEN (AGENT_CITY='CHENNAI' AND AGENT_ID REGEXP '^[M]') THEN TARGET_POLICY_SUM=250000
END
WHERE AGENT_CITY IN ('PUNR','CHENNAI',)
